In [1]:
# Importing required lib

import pandas as pd
import numpy as np

In [2]:
# Reading the dataset

df = pd.read_csv('/content/Churn_Modelling.csv')

In [3]:
# Visualizing 1st 5 data

df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# Checking for data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
# Checking for null values

df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [6]:
# Checking for state value count

df['Surname'].value_counts()
df['Geography'].value_counts()
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
# Initializing encoder

le = LabelEncoder()

In [9]:
# Transforming values

df['Surname'] = le.fit_transform(df['Surname'])
df['Geography'] = le.fit_transform(df['Geography'])
df['Gender'] = le.fit_transform(df['Gender'])

In [10]:
df.head()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602     1115          619          0       0   42   
1          2    15647311     1177          608          2       0   41   
2          3    15619304     2040          502          0       0   42   
3          4    15701354      289          699          0       0   39   
4          5    15737888     1822          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [11]:
# Split data (independent & dependent variables)

x = df.iloc[:,0:4].values
y = df.iloc[:,4:5].values

In [12]:
x

array([[       1, 15634602,     1115,      619],
       [       2, 15647311,     1177,      608],
       [       3, 15619304,     2040,      502],
       ...,
       [    9998, 15584532,     1570,      709],
       [    9999, 15682355,     2345,      772],
       [   10000, 15628319,     2751,      792]])

In [13]:
y

array([[0],
       [2],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
# Split data (train & test data)

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=0)

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [17]:
# Creating skeleton ANN model

regressor = Sequential()
regressor.add(Dense(4, activation='relu')) # Input
regressor.add(Dense(12, activation='relu')) # 1st hid. layer
regressor.add(Dense(8, activation='relu')) # 2nd hid. layer
regressor.add(Dense(9, activation='relu')) # 3rd hid. layer
regressor.add(Dense(1,activation='linear')) # output layer

In [18]:
# Passing optimizers to the model

regressor.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [19]:
# Training the model

regressor.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
700/700 [==============================] - 5s 2ms/step - loss: 14697805824.0000 - mse: 14697805824.0000
Epoch 2/300
700/700 [==============================] - 2s 2ms/step - loss: 652.1165 - mse: 652.1165
Epoch 3/300
700/700 [==============================] - 2s 2ms/step - loss: 24.8983 - mse: 24.8983
Epoch 4/300
700/700 [==============================] - 2s 2ms/step - loss: 6.7150 - mse: 6.7150
Epoch 5/300
700/700 [==============================] - 2s 2ms/step - loss: 3.2548 - mse: 3.2548
Epoch 6/300
700/700 [==============================] - 2s 2ms/step - loss: 2.1321 - mse: 2.1321
Epoch 7/300
700/700 [==============================] - 2s 2ms/step - loss: 1.7307 - mse: 1.7307
Epoch 8/300
700/700 [==============================] - 2s 2ms/step - loss: 1.5405 - mse: 1.5405
Epoch 9/300
700/700 [==============================] - 2s 2ms/step - loss: 1.4377 - mse: 1.4377
Epoch 10/300
700/700 [==============================] - 2s 2ms/step - loss: 1.3851 - mse: 1.3851
Epoch 11/300


In [20]:
# Predicting the test data

ypred = regressor.predict(xtest)

In [21]:
ypred

array([[0.75319684],
       [0.75319684],
       [0.75319684],
       ...,
       [0.75319684],
       [0.75319684],
       [0.75319684]], dtype=float32)

In [22]:
ytest

array([[1],
       [0],
       [2],
       ...,
       [0],
       [0],
       [1]])

In [23]:
# Comparing actual ytest values with predicted values

pd.DataFrame({'Actual values':ytest.flatten(),
              'Predicted values':ypred.flatten()})

Actual values  Predicted values
0                 1          0.753197
1                 0          0.753197
2                 2          0.753197
3                 0          0.753197
4                 1          0.753197
...             ...               ...
2995              2          0.753197
2996              0          0.753197
2997              0          0.753197
2998              0          0.753197
2999              1          0.753197

[3000 rows x 2 columns]

In [24]:
from sklearn.metrics import r2_score

In [25]:
# checking accuracy

r2_score(ytest,ypred)*100

-0.010567367164937558

In [26]:
regressor.predict([[1234543.34,53343445.34,5645575.3,2]])

array([[134128.28]], dtype=float32)

In [27]:
# Saving the ANN model weights (it can be used whenever we want... each and every time no need to train model)

regressor.save('regressor.h5')

In [28]:
# Reading the dataset

data = pd.read_csv('/content/Breast Cancer Wisconsin (Diagnostic) Data Set.csv')

In [29]:
# Visualizing 1st 5 data

# output column is diagnosis (M = malignant, B = benign)

data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [30]:
# Checking for data types

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [31]:
# Checking for null values

data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [32]:
# Drop unwanted columns

data.drop(['Unnamed: 32','id'],axis=1,inplace=True)

In [33]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [34]:
# Split data (independent & dependent variables)

x = data.drop(['diagnosis'],axis=1)
y = data['diagnosis']

In [35]:
# Transforming values

le2 = LabelEncoder()
y = le2.fit_transform(data['diagnosis'])

In [36]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [37]:
# Split data (train & test data)

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=0)

In [38]:
xtrain.shape

(398, 30)

In [39]:
# Creating skeleton ANN model

classification = Sequential()
classification.add(Dense(30, activation='relu')) # Input
classification.add(Dense(128, activation='relu')) # 1st hid. layer
classification.add(Dense(64, activation='relu')) # 2nd hid. layer
classification.add(Dense(32, activation='relu')) # 3rd hid. layer
classification.add(Dense(1,activation='sigmoid')) # output layer

In [40]:
# Passing optimizers to the model

classification.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [41]:
# Training the model

classification.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
40/40 [==============================] - 1s 3ms/step - loss: 1.9115 - accuracy: 0.6633
Epoch 2/300
40/40 [==============================] - 0s 3ms/step - loss: 0.3027 - accuracy: 0.9070
Epoch 3/300
40/40 [==============================] - 0s 3ms/step - loss: 0.6887 - accuracy: 0.8040
Epoch 4/300
40/40 [==============================] - 0s 3ms/step - loss: 0.5999 - accuracy: 0.8216
Epoch 5/300
40/40 [==============================] - 0s 3ms/step - loss: 0.4229 - accuracy: 0.8945
Epoch 6/300
40/40 [==============================] - 0s 3ms/step - loss: 0.3741 - accuracy: 0.8844
Epoch 7/300
40/40 [==============================] - 0s 3ms/step - loss: 0.3822 - accuracy: 0.8869
Epoch 8/300
40/40 [==============================] - 0s 3ms/step - loss: 0.3153 - accuracy: 0.8970
Epoch 9/300
40/40 [==============================] - 0s 3ms/step - loss: 0.4484 - accuracy: 0.8668
Epoch 10/300
40/40 [==============================] - 0s 3ms/step - loss: 0.2382 - accuracy: 0.9095
Epoch 11/

In [42]:
# Predicting the test data

ypred = classification.predict(xtest)

In [43]:
ypred

array([[9.63043630e-01],
       [3.12294792e-02],
       [1.44513877e-04],
       [1.15429260e-01],
       [3.50876398e-05],
       [9.28838872e-08],
       [2.54960764e-08],
       [1.68477658e-08],
       [9.82593320e-14],
       [9.64382255e-11],
       [1.06172055e-01],
       [2.41367012e-01],
       [5.76007720e-13],
       [8.66766453e-01],
       [4.13552932e-02],
       [9.88333821e-01],
       [5.99150883e-13],
       [1.00000000e+00],
       [9.98013139e-01],
       [1.00000000e+00],
       [9.99971747e-01],
       [6.95026696e-01],
       [1.24064063e-05],
       [3.15049765e-05],
       [9.91838753e-01],
       [3.33655509e-04],
       [1.63989853e-08],
       [1.72603816e-01],
       [6.28541238e-05],
       [1.00000000e+00],
       [2.20092329e-06],
       [1.00000000e+00],
       [9.82581675e-02],
       [9.99281347e-01],
       [1.17075588e-12],
       [9.99731362e-01],
       [9.47369076e-03],
       [9.99993205e-01],
       [1.76118209e-03],
       [9.99306917e-01],


In [44]:
np.round(ypred.flatten()).astype('int')

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [45]:
# Comparing actual ytest values with predicted values

pd.DataFrame({'Actual values':ytest.flatten(),
              'Predicted values':np.round(ypred.flatten()).astype('int')})

Actual values  Predicted values
0                1                 1
1                0                 0
2                0                 0
3                0                 0
4                0                 0
..             ...               ...
166              1                 1
167              1                 1
168              0                 0
169              0                 0
170              0                 0

[171 rows x 2 columns]

In [46]:
# Saving the ANN model weights (it can be used whenever we want... each and every time no need to train model)

classification.save('classification.h5')